# Generated by Django 5.0.7 on 2024-07-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=50)),
                ('stars', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('runningtime', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
            ],
        ),
    ]
