# Generated by Django 5.0.7 on 2024-07-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='runningtime',
            field=models.IntegerField(help_text='러닝타임(분)'),
        ),
    ]
