# Generated by Django 5.0.7 on 2024-07-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
