# Generated by Django 5.0.7 on 2024-07-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='expected_tools',
            field=models.CharField(choices=[('django', 'Django'), ('flask', 'Flask'), ('react', 'React'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('node', 'Node.js')], default='django', max_length=20, verbose_name='예상 개발툴'),
        ),
    ]
