# Generated by Django 5.0.7 on 2024-07-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_alter_idea_devtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='expected_tools',
            field=models.CharField(choices=[('Django', 'Django'), ('Flask', 'Flask'), ('React', 'React'), ('Vue.js', 'Vue.js'), ('Angular', 'Angular'), ('Node.js', 'Node.js')], default='django', max_length=20, verbose_name='예상 개발툴'),
        ),
    ]
