# Generated by Django 5.0.7 on 2024-07-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_created_at_idea_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='starred',
            field=models.BooleanField(default=False, verbose_name='찜하기'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록 시간'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
    ]
