# Generated by Django 5.0.7 on 2024-07-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_idea_starred_alter_idea_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='idea_images/', verbose_name='이미지'),
        ),
    ]
