# Generated by Django 5.0.7 on 2024-07-17 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
        ('ideas', '0005_alter_idea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devtools.devtool'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(default='/Users/kevinminsukim/dev/piro21th/Kim-minsoo/SWIDEA_SITE/SWIDEA_SITE/server/idea_images/piro.png', upload_to='idea_images/', verbose_name='이미지'),
            preserve_default=False,
        ),
    ]
